version: '3.4'

services:
  simplcommerce.webhost:
    image: ${DOCKER_REGISTRY-}simplcommercewebhost
    build:
      context: .
      dockerfile: Dockerfile

  database:
    image:postgres
    restart:always
    environment:
      POSTGRES_PASSWORD:postgres
      POSTGRES_USER:postgres
      POSTGRES_DB:simplcommerce
    

