version: '3.4'

services:
  simplcommerce.webhost:
    image: ${DOCKER_REGISTRY-}simplcommercewebhost
    build:
      context: .
      dockerfile: Dockerfile    
    depends_on:
        - database
    container_name: 'stormy_webhost'    
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://*:443;http://*:80
      - ASPNETCORE_HTTPS_PORT=44388
      - ASPNETCORE_Kestrel__Certificates__Default__Password="simpldevpassword"
      - ASPNETCORE_Kestrel__Certificates__Development__Password="crypticpassword"
      - ASPNETCORE_Kestrel__Certificates__Default__Path=SimplCommerce.WebHost.pfx
    networks:
      - stormy-net
    ports:
      - "49209:80"
      - "44388:443"
    volumes:      
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  database:
    image: postgres:latest
    container_name: 'postgres'    
    ports:
      - "5432"
    restart: always
    networks:
      - stormy-net
    environment:
        - "POSTGRES_PASSWORD=postgres"
        - "POSTGRES_USER=postgres"        
    volumes:
      - data:/var/lib/postgresql/data
      - ./postgresql-initdb:/docker-entrypoint-initdb.d/dbscript.sql
    networks: 
      - stormy-net
volumes:
  data:
  postgresql-initdb:
networks:
  stormy-net:
    driver: bridge