FROM microsoft/dotnet:2.2-sdk AS build-env
  
WORKDIR /app
COPY . ./
RUN dotnet build SimplCommerce.sln -c Release \
	&& cd src/SimplCommerce.WebHost \
	&& dotnet build -c Release \
	&& dotnet publish -c Release -o out

FROM microsoft/dotnet:2.2.0-aspnetcore-runtime

RUN apt-get update \
	&& apt-get install libgdiplus -y \
	&& rm -rf /var/lib/apt/lists/*

WORKDIR /app	
COPY --from=build-env /app/src/SimplCommerce.WebHost/out ./
COPY --from=build-env /app/src/SimplCommerce.WebHost/database.db ./

ENTRYPOINT ["dotnet", "SimplCommerce.WebHost.dll"]