version: '3.4'

services:
  simplcommerce.webhost:
    image: ${DOCKER_REGISTRY-}simplcommercewebhost
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "80:8000"
    depends_on:
        - database
    container_name: 'stormy_webhost'

    

  database:
    image: postgres
    container_name: 'postgres'
    restart: always
    environment:
        - "POSTGRES_PASSWORD=postgres"
        - "POSTGRES_USER=postgres"
        - "POSTGRES_DB=stormydb"

