// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StormyCommerce.Infraestructure.Data;

namespace SimplCommerce.WebHost.Migrations
{
    [DbContext(typeof(StormyDbContext))]
    [Migration("20190909024945_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("StormyCommerce.Core.Entities.Catalog.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(450);

                    b.Property<int>("DisplayOrder");

                    b.Property<bool>("IncludeInMenu");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsPublished");

                    b.Property<DateTimeOffset>("LastModified");

                    b.Property<string>("MetaDescription");

                    b.Property<string>("MetaKeywords")
                        .HasMaxLength(450);

                    b.Property<string>("MetaTitle")
                        .HasMaxLength(450);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(450);

                    b.Property<long?>("ParentId");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(450);

                    b.Property<string>("ThumbnailImageUrl");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("StormyCommerce.Core.Entities.Catalog.Product.Brand", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTimeOffset>("LastModified");

                    b.Property<string>("LogoImage");

                    b.Property<string>("Name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(450);

                    b.Property<string>("Website");

                    b.HasKey("Id");

                    b.ToTable("Brand");
                });

            modelBuilder.Entity("StormyCommerce.Core.Entities.Catalog.Product.ProductAttribute", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("GroupId");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTimeOffset>("LastModified");

                    b.Property<string>("Name");

                    b.Property<long?>("StormyProductId");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("StormyProductId");

                    b.ToTable("ProductAttribute");
                });

            modelBuilder.Entity("StormyCommerce.Core.Entities.Catalog.Product.ProductAttributeGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTimeOffset>("LastModified");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(450);

                    b.HasKey("Id");

                    b.ToTable("ProductAttributeGroup");
                });

            modelBuilder.Entity("StormyCommerce.Core.Entities.Catalog.Product.ProductAttributeValue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("AttributeId");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTimeOffset>("LastModified");

                    b.Property<long>("ProductId");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("AttributeId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductAttributeValue");
                });

            modelBuilder.Entity("StormyCommerce.Core.Entities.Catalog.Product.ProductLink", b =>
                {
                    b.Property<long>("Id");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTimeOffset>("LastModified");

                    b.Property<int>("LinkType");

                    b.Property<long>("LinkedProductId");

                    b.Property<long>("ProductId");

                    b.HasKey("Id");

                    b.HasIndex("LinkedProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductLink");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            IsDeleted = false,
                            LastModified = new DateTimeOffset(new DateTime(2019, 9, 2, 0, 59, 50, 286, DateTimeKind.Unspecified).AddTicks(7408), new TimeSpan(0, 0, 0, 0, 0)),
                            LinkType = 2,
                            LinkedProductId = 14L,
                            ProductId = 46L
                        },
                        new
                        {
                            Id = 2L,
                            IsDeleted = false,
                            LastModified = new DateTimeOffset(new DateTime(2019, 8, 19, 8, 17, 21, 910, DateTimeKind.Unspecified).AddTicks(2249), new TimeSpan(0, 0, 0, 0, 0)),
                            LinkType = 2,
                            LinkedProductId = 24L,
                            ProductId = 14L
                        },
                        new
                        {
                            Id = 3L,
                            IsDeleted = false,
                            LastModified = new DateTimeOffset(new DateTime(2019, 8, 17, 19, 39, 7, 616, DateTimeKind.Unspecified).AddTicks(5261), new TimeSpan(0, 0, 0, 0, 0)),
                            LinkType = 2,
                            LinkedProductId = 19L,
                            ProductId = 14L
                        },
                        new
                        {
                            Id = 4L,
                            IsDeleted = false,
                            LastModified = new DateTimeOffset(new DateTime(2019, 8, 29, 11, 19, 37, 189, DateTimeKind.Unspecified).AddTicks(964), new TimeSpan(0, 0, 0, 0, 0)),
                            LinkType = 2,
                            LinkedProductId = 7L,
                            ProductId = 48L
                        },
                        new
                        {
                            Id = 5L,
                            IsDeleted = false,
                            LastModified = new DateTimeOffset(new DateTime(2019, 8, 30, 3, 19, 58, 622, DateTimeKind.Unspecified).AddTicks(7133), new TimeSpan(0, 0, 0, 0, 0)),
                            LinkType = 2,
                            LinkedProductId = 42L,
                            ProductId = 25L
                        },
                        new
                        {
                            Id = 6L,
                            IsDeleted = false,
                            LastModified = new DateTimeOffset(new DateTime(2019, 8, 28, 4, 12, 18, 171, DateTimeKind.Unspecified).AddTicks(9338), new TimeSpan(0, 0, 0, 0, 0)),
                            LinkType = 2,
                            LinkedProductId = 39L,
                            ProductId = 35L
                        },
                        new
                        {
                            Id = 7L,
                            IsDeleted = false,
                            LastModified = new DateTimeOffset(new DateTime(2019, 8, 24, 22, 14, 28, 525, DateTimeKind.Unspecified).AddTicks(3947), new TimeSpan(0, 0, 0, 0, 0)),
                            LinkType = 2,
                            LinkedProductId = 50L,
                            ProductId = 17L
                        },
                        new
                        {
                            Id = 8L,
                            IsDeleted = false,
                            LastModified = new DateTimeOffset(new DateTime(2019, 9, 3, 15, 12, 31, 442, DateTimeKind.Unspecified).AddTicks(281), new TimeSpan(0, 0, 0, 0, 0)),
                            LinkType = 2,
                            LinkedProductId = 10L,
                            ProductId = 15L
                        },
                        new
                        {
                            Id = 9L,
                            IsDeleted = false,
                            LastModified = new DateTimeOffset(new DateTime(2019, 8, 16, 1, 21, 49, 26, DateTimeKind.Unspecified).AddTicks(6192), new TimeSpan(0, 0, 0, 0, 0)),
                            LinkType = 2,
                            LinkedProductId = 17L,
                            ProductId = 1L
                        },
                        new
                        {
                            Id = 10L,
                            IsDeleted = false,
                            LastModified = new DateTimeOffset(new DateTime(2019, 8, 24, 7, 52, 15, 57, DateTimeKind.Unspecified).AddTicks(2446), new TimeSpan(0, 0, 0, 0, 0)),
                            LinkType = 2,
                            LinkedProductId = 27L,
                            ProductId = 19L
                        },
                        new
                        {
                            Id = 11L,
                            IsDeleted = false,
                            LastModified = new DateTimeOffset(new DateTime(2019, 8, 28, 2, 6, 34, 844, DateTimeKind.Unspecified).AddTicks(3273), new TimeSpan(0, 0, 0, 0, 0)),
                            LinkType = 2,
                            LinkedProductId = 40L,
                            ProductId = 46L
                        },
                        new
                        {
                            Id = 12L,
                            IsDeleted = false,
                            LastModified = new DateTimeOffset(new DateTime(2019, 9, 8, 16, 16, 28, 678, DateTimeKind.Unspecified).AddTicks(9265), new TimeSpan(0, 0, 0, 0, 0)),
                            LinkType = 2,
                            LinkedProductId = 27L,
                            ProductId = 18L
                        },
                        new
                        {
                            Id = 13L,
                            IsDeleted = false,
                            LastModified = new DateTimeOffset(new DateTime(2019, 8, 18, 13, 37, 57, 636, DateTimeKind.Unspecified).AddTicks(6499), new TimeSpan(0, 0, 0, 0, 0)),
                            LinkType = 2,
                            LinkedProductId = 11L,
                            ProductId = 47L
                        },
                        new
                        {
                            Id = 14L,
                            IsDeleted = false,
                            LastModified = new DateTimeOffset(new DateTime(2019, 9, 7, 6, 21, 28, 851, DateTimeKind.Unspecified).AddTicks(3121), new TimeSpan(0, 0, 0, 0, 0)),
                            LinkType = 2,
                            LinkedProductId = 12L,
                            ProductId = 21L
                        },
                        new
                        {
                            Id = 15L,
                            IsDeleted = false,
                            LastModified = new DateTimeOffset(new DateTime(2019, 9, 6, 17, 50, 19, 183, DateTimeKind.Unspecified).AddTicks(2627), new TimeSpan(0, 0, 0, 0, 0)),
                            LinkType = 2,
                            LinkedProductId = 1L,
                            ProductId = 33L
                        },
                        new
                        {
                            Id = 16L,
                            IsDeleted = false,
                            LastModified = new DateTimeOffset(new DateTime(2019, 9, 5, 23, 54, 54, 84, DateTimeKind.Unspecified).AddTicks(6220), new TimeSpan(0, 0, 0, 0, 0)),
                            LinkType = 2,
                            LinkedProductId = 39L,
                            ProductId = 4L
                        },
                        new
                        {
                            Id = 17L,
                            IsDeleted = false,
                            LastModified = new DateTimeOffset(new DateTime(2019, 8, 20, 7, 38, 58, 87, DateTimeKind.Unspecified).AddTicks(6651), new TimeSpan(0, 0, 0, 0, 0)),
                            LinkType = 2,
                            LinkedProductId = 14L,
                            ProductId = 17L
                        },
                        new
                        {
                            Id = 18L,
                            IsDeleted = false,
                            LastModified = new DateTimeOffset(new DateTime(2019, 9, 4, 14, 46, 2, 242, DateTimeKind.Unspecified).AddTicks(3976), new TimeSpan(0, 0, 0, 0, 0)),
                            LinkType = 2,
                            LinkedProductId = 40L,
                            ProductId = 28L
                        },
                        new
                        {
                            Id = 19L,
                            IsDeleted = false,
                            LastModified = new DateTimeOffset(new DateTime(2019, 8, 17, 13, 8, 55, 170, DateTimeKind.Unspecified).AddTicks(6456), new TimeSpan(0, 0, 0, 0, 0)),
                            LinkType = 2,
                            LinkedProductId = 4L,
                            ProductId = 5L
                        },
                        new
                        {
                            Id = 20L,
                            IsDeleted = false,
                            LastModified = new DateTimeOffset(new DateTime(2019, 8, 25, 0, 7, 31, 127, DateTimeKind.Unspecified).AddTicks(9667), new TimeSpan(0, 0, 0, 0, 0)),
                            LinkType = 2,
                            LinkedProductId = 44L,
                            ProductId = 8L
                        },
                        new
                        {
                            Id = 21L,
                            IsDeleted = false,
                            LastModified = new DateTimeOffset(new DateTime(2019, 9, 2, 11, 35, 26, 560, DateTimeKind.Unspecified).AddTicks(8789), new TimeSpan(0, 0, 0, 0, 0)),
                            LinkType = 2,
                            LinkedProductId = 14L,
                            ProductId = 43L
                        },
                        new
                        {
                            Id = 22L,
                            IsDeleted = false,
                            LastModified = new DateTimeOffset(new DateTime(2019, 8, 17, 4, 43, 52, 204, DateTimeKind.Unspecified).AddTicks(8530), new TimeSpan(0, 0, 0, 0, 0)),
                            LinkType = 2,
                            LinkedProductId = 48L,
                            ProductId = 18L
                        },
                        new
                        {
                            Id = 23L,
                            IsDeleted = false,
                            LastModified = new DateTimeOffset(new DateTime(2019, 9, 7, 20, 44, 52, 526, DateTimeKind.Unspecified).AddTicks(3294), new TimeSpan(0, 0, 0, 0, 0)),
                            LinkType = 2,
                            LinkedProductId = 20L,
                            ProductId = 15L
                        },
                        new
                        {
                            Id = 24L,
                            IsDeleted = false,
                            LastModified = new DateTimeOffset(new DateTime(2019, 9, 5, 19, 33, 47, 700, DateTimeKind.Unspecified).AddTicks(975), new TimeSpan(0, 0, 0, 0, 0)),
                            LinkType = 2,
                            LinkedProductId = 31L,
                            ProductId = 29L
                        },
                        new
                        {
                            Id = 25L,
                            IsDeleted = false,
                            LastModified = new DateTimeOffset(new DateTime(2019, 8, 21, 1, 13, 5, 120, DateTimeKind.Unspecified).AddTicks(4496), new TimeSpan(0, 0, 0, 0, 0)),
                            LinkType = 2,
                            LinkedProductId = 27L,
                            ProductId = 38L
                        },
                        new
                        {
                            Id = 26L,
                            IsDeleted = false,
                            LastModified = new DateTimeOffset(new DateTime(2019, 8, 17, 1, 25, 38, 946, DateTimeKind.Unspecified).AddTicks(974), new TimeSpan(0, 0, 0, 0, 0)),
                            LinkType = 2,
                            LinkedProductId = 7L,
                            ProductId = 10L
                        },
                        new
                        {
                            Id = 27L,
                            IsDeleted = false,
                            LastModified = new DateTimeOffset(new DateTime(2019, 8, 23, 21, 53, 57, 34, DateTimeKind.Unspecified).AddTicks(3563), new TimeSpan(0, 0, 0, 0, 0)),
                            LinkType = 2,
                            LinkedProductId = 42L,
                            ProductId = 29L
                        },
                        new
                        {
                            Id = 28L,
                            IsDeleted = false,
                            LastModified = new DateTimeOffset(new DateTime(2019, 8, 16, 23, 30, 32, 602, DateTimeKind.Unspecified).AddTicks(5657), new TimeSpan(0, 0, 0, 0, 0)),
                            LinkType = 2,
                            LinkedProductId = 42L,
                            ProductId = 13L
                        },
                        new
                        {
                            Id = 29L,
                            IsDeleted = false,
                            LastModified = new DateTimeOffset(new DateTime(2019, 9, 8, 6, 5, 27, 613, DateTimeKind.Unspecified).AddTicks(5065), new TimeSpan(0, 0, 0, 0, 0)),
                            LinkType = 2,
                            LinkedProductId = 16L,
                            ProductId = 50L
                        },
                        new
                        {
                            Id = 30L,
                            IsDeleted = false,
                            LastModified = new DateTimeOffset(new DateTime(2019, 8, 30, 23, 50, 55, 499, DateTimeKind.Unspecified).AddTicks(4615), new TimeSpan(0, 0, 0, 0, 0)),
                            LinkType = 2,
                            LinkedProductId = 6L,
                            ProductId = 24L
                        },
                        new
                        {
                            Id = 31L,
                            IsDeleted = false,
                            LastModified = new DateTimeOffset(new DateTime(2019, 9, 2, 10, 8, 16, 511, DateTimeKind.Unspecified).AddTicks(8473), new TimeSpan(0, 0, 0, 0, 0)),
                            LinkType = 2,
                            LinkedProductId = 13L,
                            ProductId = 18L
                        },
                        new
                        {
                            Id = 32L,
                            IsDeleted = false,
                            LastModified = new DateTimeOffset(new DateTime(2019, 8, 20, 11, 10, 20, 497, DateTimeKind.Unspecified).AddTicks(3268), new TimeSpan(0, 0, 0, 0, 0)),
                            LinkType = 2,
                            LinkedProductId = 41L,
                            ProductId = 49L
                        },
                        new
                        {
                            Id = 33L,
                            IsDeleted = false,
                            LastModified = new DateTimeOffset(new DateTime(2019, 8, 25, 23, 17, 35, 599, DateTimeKind.Unspecified).AddTicks(2357), new TimeSpan(0, 0, 0, 0, 0)),
                            LinkType = 2,
                            LinkedProductId = 9L,
                            ProductId = 4L
                        },
                        new
                        {
                            Id = 34L,
                            IsDeleted = false,
                            LastModified = new DateTimeOffset(new DateTime(2019, 9, 1, 9, 34, 32, 922, DateTimeKind.Unspecified).AddTicks(8342), new TimeSpan(0, 0, 0, 0, 0)),
                            LinkType = 2,
                            LinkedProductId = 4L,
                            ProductId = 20L
                        },
                        new
                        {
                            Id = 35L,
                            IsDeleted = false,
                            LastModified = new DateTimeOffset(new DateTime(2019, 8, 20, 9, 22, 40, 249, DateTimeKind.Unspecified).AddTicks(7369), new TimeSpan(0, 0, 0, 0, 0)),
                            LinkType = 2,
                            LinkedProductId = 33L,
                            ProductId = 33L
                        },
                        new
                        {
                            Id = 36L,
                            IsDeleted = false,
                            LastModified = new DateTimeOffset(new DateTime(2019, 8, 20, 22, 3, 49, 845, DateTimeKind.Unspecified).AddTicks(1379), new TimeSpan(0, 0, 0, 0, 0)),
                            LinkType = 2,
                            LinkedProductId = 21L,
                            ProductId = 13L
                        },
                        new
                        {
                            Id = 37L,
                            IsDeleted = false,
                            LastModified = new DateTimeOffset(new DateTime(2019, 8, 20, 8, 1, 59, 741, DateTimeKind.Unspecified).AddTicks(9000), new TimeSpan(0, 0, 0, 0, 0)),
                            LinkType = 2,
                            LinkedProductId = 50L,
                            ProductId = 47L
                        },
                        new
                        {
                            Id = 38L,
                            IsDeleted = false,
                            LastModified = new DateTimeOffset(new DateTime(2019, 8, 17, 14, 23, 3, 388, DateTimeKind.Unspecified).AddTicks(4099), new TimeSpan(0, 0, 0, 0, 0)),
                            LinkType = 2,
                            LinkedProductId = 48L,
                            ProductId = 2L
                        },
                        new
                        {
                            Id = 39L,
                            IsDeleted = false,
                            LastModified = new DateTimeOffset(new DateTime(2019, 8, 25, 18, 25, 37, 389, DateTimeKind.Unspecified).AddTicks(1007), new TimeSpan(0, 0, 0, 0, 0)),
                            LinkType = 2,
                            LinkedProductId = 17L,
                            ProductId = 22L
                        },
                        new
                        {
                            Id = 40L,
                            IsDeleted = false,
                            LastModified = new DateTimeOffset(new DateTime(2019, 8, 25, 12, 28, 14, 501, DateTimeKind.Unspecified).AddTicks(9822), new TimeSpan(0, 0, 0, 0, 0)),
                            LinkType = 2,
                            LinkedProductId = 45L,
                            ProductId = 33L
                        },
                        new
                        {
                            Id = 41L,
                            IsDeleted = false,
                            LastModified = new DateTimeOffset(new DateTime(2019, 8, 31, 7, 57, 43, 732, DateTimeKind.Unspecified).AddTicks(7630), new TimeSpan(0, 0, 0, 0, 0)),
                            LinkType = 2,
                            LinkedProductId = 35L,
                            ProductId = 14L
                        },
                        new
                        {
                            Id = 42L,
                            IsDeleted = false,
                            LastModified = new DateTimeOffset(new DateTime(2019, 8, 19, 13, 10, 9, 482, DateTimeKind.Unspecified).AddTicks(5964), new TimeSpan(0, 0, 0, 0, 0)),
                            LinkType = 2,
                            LinkedProductId = 44L,
                            ProductId = 18L
                        },
                        new
                        {
                            Id = 43L,
                            IsDeleted = false,
                            LastModified = new DateTimeOffset(new DateTime(2019, 9, 3, 16, 17, 43, 569, DateTimeKind.Unspecified).AddTicks(4204), new TimeSpan(0, 0, 0, 0, 0)),
                            LinkType = 2,
                            LinkedProductId = 49L,
                            ProductId = 37L
                        },
                        new
                        {
                            Id = 44L,
                            IsDeleted = false,
                            LastModified = new DateTimeOffset(new DateTime(2019, 8, 20, 12, 51, 54, 315, DateTimeKind.Unspecified).AddTicks(6612), new TimeSpan(0, 0, 0, 0, 0)),
                            LinkType = 2,
                            LinkedProductId = 18L,
                            ProductId = 48L
                        },
                        new
                        {
                            Id = 45L,
                            IsDeleted = false,
                            LastModified = new DateTimeOffset(new DateTime(2019, 9, 6, 1, 38, 28, 328, DateTimeKind.Unspecified).AddTicks(8561), new TimeSpan(0, 0, 0, 0, 0)),
                            LinkType = 2,
                            LinkedProductId = 17L,
                            ProductId = 39L
                        },
                        new
                        {
                            Id = 46L,
                            IsDeleted = false,
                            LastModified = new DateTimeOffset(new DateTime(2019, 9, 4, 15, 54, 19, 432, DateTimeKind.Unspecified).AddTicks(1271), new TimeSpan(0, 0, 0, 0, 0)),
                            LinkType = 2,
                            LinkedProductId = 7L,
                            ProductId = 9L
                        },
                        new
                        {
                            Id = 47L,
                            IsDeleted = false,
                            LastModified = new DateTimeOffset(new DateTime(2019, 8, 25, 2, 38, 10, 312, DateTimeKind.Unspecified).AddTicks(6151), new TimeSpan(0, 0, 0, 0, 0)),
                            LinkType = 2,
                            LinkedProductId = 14L,
                            ProductId = 45L
                        },
                        new
                        {
                            Id = 48L,
                            IsDeleted = false,
                            LastModified = new DateTimeOffset(new DateTime(2019, 8, 21, 20, 50, 56, 949, DateTimeKind.Unspecified).AddTicks(867), new TimeSpan(0, 0, 0, 0, 0)),
                            LinkType = 2,
                            LinkedProductId = 29L,
                            ProductId = 7L
                        },
                        new
                        {
                            Id = 49L,
                            IsDeleted = false,
                            LastModified = new DateTimeOffset(new DateTime(2019, 8, 26, 22, 10, 4, 686, DateTimeKind.Unspecified).AddTicks(9700), new TimeSpan(0, 0, 0, 0, 0)),
                            LinkType = 2,
                            LinkedProductId = 19L,
                            ProductId = 16L
                        },
                        new
                        {
                            Id = 50L,
                            IsDeleted = false,
                            LastModified = new DateTimeOffset(new DateTime(2019, 9, 1, 7, 44, 26, 61, DateTimeKind.Unspecified).AddTicks(7273), new TimeSpan(0, 0, 0, 0, 0)),
                            LinkType = 2,
                            LinkedProductId = 11L,
                            ProductId = 24L
                        });
                });

            modelBuilder.Entity("StormyCommerce.Core.Entities.Catalog.Product.ProductOption", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTimeOffset>("LastModified");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(450);

                    b.HasKey("Id");

                    b.ToTable("ProductOption");
                });

            modelBuilder.Entity("StormyCommerce.Core.Entities.Catalog.Product.ProductOptionValue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DisplayType")
                        .HasMaxLength(450);

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTimeOffset>("LastModified");

                    b.Property<long>("OptionId");

                    b.Property<long>("ProductId");

                    b.Property<int>("SortIndex");

                    b.Property<string>("Value")
                        .HasMaxLength(450);

                    b.HasKey("Id");

                    b.HasIndex("OptionId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductOptionValue");
                });

            modelBuilder.Entity("StormyCommerce.Core.Entities.Catalog.Product.ProductTemplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTimeOffset>("LastModified");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("ProductTemplate");
                });

            modelBuilder.Entity("StormyCommerce.Core.Entities.Catalog.Product.ProductTemplateProductAttribute", b =>
                {
                    b.Property<long>("ProductTemplateId");

                    b.Property<long>("ProductAttributeId");

                    b.HasKey("ProductTemplateId", "ProductAttributeId");

                    b.HasIndex("ProductAttributeId");

                    b.ToTable("ProductTemplateProductAttribute");
                });

            modelBuilder.Entity("StormyCommerce.Core.Entities.Catalog.Product.StormyProduct", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("AllowCustomerReview");

                    b.Property<int>("ApprovedRatingSum");

                    b.Property<int>("ApprovedTotalReviews");

                    b.Property<bool>("AvailableForPreorder");

                    b.Property<long>("BrandId");

                    b.Property<long>("CategoryId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<decimal>("Discount");

                    b.Property<bool>("DiscountAvailable");

                    b.Property<bool>("HasDiscountApplied");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTimeOffset>("LastModified");

                    b.Property<long>("MediaId");

                    b.Property<int>("NotApprovedRatingSum");

                    b.Property<int>("NotApprovedTotalReviews");

                    b.Property<bool>("NotReturnable");

                    b.Property<string>("Note");

                    b.Property<string>("OldPrice");

                    b.Property<DateTime?>("PreOrderAvailabilityStartDate");

                    b.Property<string>("Price");

                    b.Property<bool>("ProductAvailable");

                    b.Property<decimal>("ProductCost");

                    b.Property<long>("ProductLinksId");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(400);

                    b.Property<bool>("Published");

                    b.Property<int>("QuantityPerUnity");

                    b.Property<int>("Ranking");

                    b.Property<string>("SKU")
                        .IsRequired();

                    b.Property<string>("Slug");

                    b.Property<string>("Status")
                        .IsRequired();

                    b.Property<bool>("StockTrackingIsEnabled");

                    b.Property<string>("ThumbnailImage");

                    b.Property<string>("TypeName")
                        .IsRequired();

                    b.Property<decimal>("UnitPrice");

                    b.Property<decimal>("UnitSize");

                    b.Property<double>("UnitWeight");

                    b.Property<int>("UnitsInStock");

                    b.Property<int>("UnitsOnOrder");

                    b.Property<DateTime>("UpdatedOnUtc");

                    b.Property<long>("VendorId");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId")
                        .IsUnique();

                    b.HasIndex("VendorId");

                    b.ToTable("StormyProduct");
                });

            modelBuilder.Entity("StormyCommerce.Core.Entities.Common.Address", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City")
                        .HasMaxLength(500);

                    b.Property<string>("Complement")
                        .HasMaxLength(250);

                    b.Property<string>("Country");

                    b.Property<string>("District");

                    b.Property<string>("FirstAddress")
                        .HasMaxLength(250);

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTimeOffset>("LastModified");

                    b.Property<string>("Number");

                    b.Property<long>("OwnerId");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(9);

                    b.Property<string>("SecondAddress")
                        .HasMaxLength(250);

                    b.Property<string>("State");

                    b.Property<string>("Street");

                    b.Property<string>("WhoReceives");

                    b.HasKey("Id");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("StormyCommerce.Core.Entities.Customer.StormyCustomer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CPF")
                        .HasMaxLength(9);

                    b.Property<DateTimeOffset>("CreatedOn");

                    b.Property<long>("CustomerReviewsId");

                    b.Property<long>("CustomerWishlistId");

                    b.Property<long?>("DefaultBillingAddressId");

                    b.Property<long?>("DefaultShippingAddressId");

                    b.Property<string>("Email");

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FullName")
                        .HasMaxLength(450);

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTimeOffset>("LastModified");

                    b.Property<string>("NormalizedEmail");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("UserId");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.HasIndex("CustomerWishlistId")
                        .IsUnique();

                    b.HasIndex("DefaultBillingAddressId");

                    b.HasIndex("DefaultShippingAddressId");

                    b.ToTable("StormyCustomer");
                });

            modelBuilder.Entity("StormyCommerce.Core.Entities.Customer.Wishlist", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CustomerId");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTimeOffset>("LastModified");

                    b.HasKey("Id");

                    b.ToTable("Wishlist");
                });

            modelBuilder.Entity("StormyCommerce.Core.Entities.Customer.WishlistItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AddedAt");

                    b.Property<bool>("Deleted");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTimeOffset>("LastModified");

                    b.Property<int>("ProductId");

                    b.Property<long?>("ProductId1");

                    b.Property<long>("WishlistId");

                    b.HasKey("Id");

                    b.HasIndex("ProductId1");

                    b.HasIndex("WishlistId");

                    b.ToTable("WishlistItem");
                });

            modelBuilder.Entity("StormyCommerce.Core.Entities.Entity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("EntityId");

                    b.Property<string>("EntityTypeId")
                        .IsRequired()
                        .HasMaxLength(450);

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTimeOffset>("LastModified");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(450);

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(450);

                    b.HasKey("Id");

                    b.HasIndex("EntityTypeId");

                    b.ToTable("Entity");
                });

            modelBuilder.Entity("StormyCommerce.Core.Entities.EntityType", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450);

                    b.Property<string>("AreaName")
                        .HasMaxLength(450);

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsMenuable");

                    b.Property<string>("RoutingAction")
                        .HasMaxLength(450);

                    b.Property<string>("RoutingController")
                        .HasMaxLength(450);

                    b.HasKey("Id");

                    b.ToTable("EntityType");
                });

            modelBuilder.Entity("StormyCommerce.Core.Entities.Media.Media", b =>
                {
                    b.Property<long>("Id");

                    b.Property<string>("Caption");

                    b.Property<string>("FileName");

                    b.Property<int>("FileSize");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTimeOffset>("LastModified");

                    b.Property<int>("MediaType");

                    b.Property<string>("SeoFileName");

                    b.HasKey("Id");

                    b.ToTable("Media");
                });

            modelBuilder.Entity("StormyCommerce.Core.Entities.Order.OrderItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTimeOffset>("LastModified");

                    b.Property<string>("Price");

                    b.Property<string>("ProductName");

                    b.Property<int>("Quantity");

                    b.Property<long>("ShipmentId");

                    b.Property<long>("StormyOrderId");

                    b.Property<long>("StormyProductId");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentId");

                    b.HasIndex("StormyOrderId");

                    b.HasIndex("StormyProductId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("StormyCommerce.Core.Entities.Payments.Payment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Amount");

                    b.Property<DateTimeOffset>("CreatedOn");

                    b.Property<string>("FailureMessage");

                    b.Property<string>("GatewayTransactionId");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTimeOffset>("LastModified");

                    b.Property<decimal>("PaymentFee");

                    b.Property<string>("PaymentMethod");

                    b.Property<int>("PaymentStatus");

                    b.Property<long>("StormyOrderId");

                    b.HasKey("Id");

                    b.HasIndex("StormyOrderId")
                        .IsUnique();

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("StormyCommerce.Core.Entities.Review", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Comment");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTimeOffset>("LastModified");

                    b.Property<int>("RatingLevel");

                    b.Property<string>("ReviewerName");

                    b.Property<long>("StormyCustomerId");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("StormyCustomerId");

                    b.ToTable("Review");
                });

            modelBuilder.Entity("StormyCommerce.Core.Entities.Settings.AppSettings", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsVisibleInCommonSettingPage");

                    b.Property<string>("Module")
                        .HasMaxLength(450);

                    b.Property<string>("Value")
                        .HasMaxLength(450);

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("StormyCommerce.Core.Entities.Shipment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("BillingAddressId");

                    b.Property<string>("Comment");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<decimal>("DeliveryCost");

                    b.Property<DateTime>("DeliveryDate");

                    b.Property<long>("DestinationAddressId");

                    b.Property<decimal>("Diameter");

                    b.Property<decimal>("Height");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTimeOffset>("LastModified");

                    b.Property<decimal>("Price");

                    b.Property<string>("ShipmentMethod");

                    b.Property<string>("ShipmentProviderName");

                    b.Property<DateTime>("ShippedDate");

                    b.Property<long>("StormyCustomerId");

                    b.Property<decimal>("TotalWeight");

                    b.Property<string>("TrackNumber")
                        .HasMaxLength(250);

                    b.Property<string>("UserId");

                    b.Property<string>("WhoReceives");

                    b.Property<decimal>("Width");

                    b.HasKey("Id");

                    b.HasIndex("BillingAddressId");

                    b.HasIndex("DestinationAddressId");

                    b.HasIndex("StormyCustomerId");

                    b.ToTable("Shipment");

                    b.HasData(
                        new
                        {
                            Id = 2L,
                            BillingAddressId = 0L,
                            Comment = "a single comment",
                            CreatedOn = new DateTime(2019, 9, 9, 2, 49, 44, 456, DateTimeKind.Utc).AddTicks(9537),
                            DeliveryCost = 22.29m,
                            DeliveryDate = new DateTime(2019, 9, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            DestinationAddressId = 0L,
                            Diameter = 0m,
                            Height = 0m,
                            IsDeleted = false,
                            LastModified = new DateTimeOffset(new DateTime(2019, 9, 9, 2, 49, 44, 456, DateTimeKind.Unspecified).AddTicks(8597), new TimeSpan(0, 0, 0, 0, 0)),
                            Price = 20.99m,
                            ShippedDate = new DateTime(2019, 9, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            StormyCustomerId = 0L,
                            TotalWeight = 0.400m,
                            TrackNumber = "a4b83b71-a4ba-4d0b-81db-d9ad6365810e",
                            Width = 0m
                        });
                });

            modelBuilder.Entity("StormyCommerce.Core.Entities.Shipping.ShipmentItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTimeOffset>("LastModified");

                    b.Property<int>("OrderItemId");

                    b.Property<int>("Quantity");

                    b.Property<int>("ShipmentId");

                    b.Property<long?>("ShipmentId1");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentId1");

                    b.ToTable("ShipmentItem");
                });

            modelBuilder.Entity("StormyCommerce.Core.Entities.StormyOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Comment");

                    b.Property<long>("CustomerId");

                    b.Property<decimal>("DeliveryCost");

                    b.Property<DateTime>("DeliveryDate");

                    b.Property<decimal>("Discount");

                    b.Property<bool>("IsCancelled");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTimeOffset>("LastModified");

                    b.Property<string>("Note")
                        .HasMaxLength(1000);

                    b.Property<DateTime>("OrderDate");

                    b.Property<Guid>("OrderUniqueKey");

                    b.Property<DateTime?>("PaymentDate");

                    b.Property<long>("PaymentId");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(450);

                    b.Property<bool>("PickUpInStore");

                    b.Property<DateTime>("RequiredDate");

                    b.Property<long>("ShipmentId");

                    b.Property<DateTime>("ShippedDate");

                    b.Property<long?>("ShippingAddressId");

                    b.Property<string>("ShippingMethod");

                    b.Property<int>("ShippingStatus");

                    b.Property<int>("Status");

                    b.Property<decimal>("Tax");

                    b.Property<decimal>("TotalPrice");

                    b.Property<decimal>("TotalWeight");

                    b.Property<string>("TrackNumber");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ShipmentId");

                    b.HasIndex("ShippingAddressId");

                    b.ToTable("StormyOrder");
                });

            modelBuilder.Entity("StormyCommerce.Core.Entities.Vendor.StormyVendor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AddressId");

                    b.Property<long?>("AddressId1");

                    b.Property<string>("CompanyName");

                    b.Property<string>("ContactTitle");

                    b.Property<string>("Email");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTimeOffset>("LastModified");

                    b.Property<string>("Logo");

                    b.Property<string>("Note");

                    b.Property<string>("Phone");

                    b.Property<string>("SizeUrl");

                    b.Property<string>("TypeGoods");

                    b.Property<string>("WebSite");

                    b.HasKey("Id");

                    b.HasIndex("AddressId1");

                    b.ToTable("StormyVendor");
                });

            modelBuilder.Entity("StormyCommerce.Infraestructure.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp");

                    b.Property<string>("Email");

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail");

                    b.Property<string>("NormalizedUserName");

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("ApplicationUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("StormyCommerce.Core.Entities.Catalog.Category", b =>
                {
                    b.HasOne("StormyCommerce.Core.Entities.Catalog.Category", "Parent")
                        .WithMany("Childrens")
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("StormyCommerce.Core.Entities.Catalog.Product.ProductAttribute", b =>
                {
                    b.HasOne("StormyCommerce.Core.Entities.Catalog.Product.ProductAttributeGroup", "Group")
                        .WithMany("Attributes")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StormyCommerce.Core.Entities.Catalog.Product.StormyProduct")
                        .WithMany("ProductAttributes")
                        .HasForeignKey("StormyProductId");
                });

            modelBuilder.Entity("StormyCommerce.Core.Entities.Catalog.Product.ProductAttributeValue", b =>
                {
                    b.HasOne("StormyCommerce.Core.Entities.Catalog.Product.ProductAttribute", "Attribute")
                        .WithMany()
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StormyCommerce.Core.Entities.Catalog.Product.StormyProduct", "Product")
                        .WithMany("AttributeValues")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("StormyCommerce.Core.Entities.Catalog.Product.ProductLink", b =>
                {
                    b.HasOne("StormyCommerce.Core.Entities.Catalog.Product.StormyProduct")
                        .WithMany("Links")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StormyCommerce.Core.Entities.Catalog.Product.StormyProduct", "LinkedProduct")
                        .WithMany("LinkedProductLinks")
                        .HasForeignKey("LinkedProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StormyCommerce.Core.Entities.Catalog.Product.StormyProduct", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("StormyCommerce.Core.Entities.Catalog.Product.ProductOptionValue", b =>
                {
                    b.HasOne("StormyCommerce.Core.Entities.Catalog.Product.ProductOption", "Option")
                        .WithMany()
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StormyCommerce.Core.Entities.Catalog.Product.StormyProduct", "Product")
                        .WithMany("OptionValues")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("StormyCommerce.Core.Entities.Catalog.Product.ProductTemplateProductAttribute", b =>
                {
                    b.HasOne("StormyCommerce.Core.Entities.Catalog.Product.ProductAttribute", "ProductAttribute")
                        .WithMany("ProductTemplates")
                        .HasForeignKey("ProductAttributeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StormyCommerce.Core.Entities.Catalog.Product.ProductTemplate", "ProductTemplate")
                        .WithMany("ProductAttributes")
                        .HasForeignKey("ProductTemplateId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("StormyCommerce.Core.Entities.Catalog.Product.StormyProduct", b =>
                {
                    b.HasOne("StormyCommerce.Core.Entities.Catalog.Product.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StormyCommerce.Core.Entities.Catalog.Category", "Category")
                        .WithOne()
                        .HasForeignKey("StormyCommerce.Core.Entities.Catalog.Product.StormyProduct", "CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StormyCommerce.Core.Entities.Vendor.StormyVendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("StormyCommerce.Core.Entities.Customer.StormyCustomer", b =>
                {
                    b.HasOne("StormyCommerce.Core.Entities.Customer.Wishlist", "CustomerWishlist")
                        .WithOne("Customer")
                        .HasForeignKey("StormyCommerce.Core.Entities.Customer.StormyCustomer", "CustomerWishlistId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StormyCommerce.Core.Entities.Common.Address", "DefaultBillingAddress")
                        .WithMany()
                        .HasForeignKey("DefaultBillingAddressId");

                    b.HasOne("StormyCommerce.Core.Entities.Common.Address", "DefaultShippingAddress")
                        .WithMany()
                        .HasForeignKey("DefaultShippingAddressId");
                });

            modelBuilder.Entity("StormyCommerce.Core.Entities.Customer.WishlistItem", b =>
                {
                    b.HasOne("StormyCommerce.Core.Entities.Catalog.Product.StormyProduct", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId1");

                    b.HasOne("StormyCommerce.Core.Entities.Customer.Wishlist", "Wishlist")
                        .WithMany("WishlistItems")
                        .HasForeignKey("WishlistId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("StormyCommerce.Core.Entities.Entity", b =>
                {
                    b.HasOne("StormyCommerce.Core.Entities.EntityType", "EntityType")
                        .WithMany()
                        .HasForeignKey("EntityTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("StormyCommerce.Core.Entities.Media.Media", b =>
                {
                    b.HasOne("StormyCommerce.Core.Entities.Catalog.Product.StormyProduct")
                        .WithMany("Medias")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("StormyCommerce.Core.Entities.Order.OrderItem", b =>
                {
                    b.HasOne("StormyCommerce.Core.Entities.Shipment", "Shipment")
                        .WithMany()
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StormyCommerce.Core.Entities.StormyOrder", "Order")
                        .WithMany("Items")
                        .HasForeignKey("StormyOrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StormyCommerce.Core.Entities.Catalog.Product.StormyProduct", "Product")
                        .WithMany()
                        .HasForeignKey("StormyProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("StormyCommerce.Core.Entities.Payments.Payment", b =>
                {
                    b.HasOne("StormyCommerce.Core.Entities.StormyOrder", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("StormyCommerce.Core.Entities.Payments.Payment", "StormyOrderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("StormyCommerce.Core.Entities.Review", b =>
                {
                    b.HasOne("StormyCommerce.Core.Entities.Customer.StormyCustomer", "Author")
                        .WithMany("CustomerReviews")
                        .HasForeignKey("StormyCustomerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("StormyCommerce.Core.Entities.Shipment", b =>
                {
                    b.HasOne("StormyCommerce.Core.Entities.Common.Address", "BillingAddress")
                        .WithMany()
                        .HasForeignKey("BillingAddressId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StormyCommerce.Core.Entities.Common.Address", "DestinationAddress")
                        .WithMany()
                        .HasForeignKey("DestinationAddressId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StormyCommerce.Core.Entities.Customer.StormyCustomer", "Customer")
                        .WithMany()
                        .HasForeignKey("StormyCustomerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("StormyCommerce.Core.Entities.Shipping.ShipmentItem", b =>
                {
                    b.HasOne("StormyCommerce.Core.Entities.Shipment", "Shipment")
                        .WithMany("Items")
                        .HasForeignKey("ShipmentId1");
                });

            modelBuilder.Entity("StormyCommerce.Core.Entities.StormyOrder", b =>
                {
                    b.HasOne("StormyCommerce.Core.Entities.Customer.StormyCustomer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StormyCommerce.Core.Entities.Shipment", "Shipment")
                        .WithMany()
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StormyCommerce.Core.Entities.Common.Address", "ShippingAddress")
                        .WithMany()
                        .HasForeignKey("ShippingAddressId");
                });

            modelBuilder.Entity("StormyCommerce.Core.Entities.Vendor.StormyVendor", b =>
                {
                    b.HasOne("StormyCommerce.Core.Entities.Common.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId1");
                });
#pragma warning restore 612, 618
        }
    }
}
